### ISSUE TITLE
Do you consider using C++'s template?

### ISSUE THREAD

**Issue by Rratic** [scandum/quadsort#12]
Genericity in C++(template)is quite useful.

Making it more useful won't hurt.

**Comment by scandum** [comment]
There's someone working on a C++ port, but since quadsort is heavy on pointer usage it's not easy for the average person to port.

I do have a quadsort update ready for release that adds 8, 16, and 128 bit support.

**Comment by Rratic** [comment]
That's intersting!
Maybe the algo can extend to octasort or even 2^n sort?
For example,if it's 1024 bit ( (2^5)^2 ),we can try 2^5 sort?
(Only thinking

**Comment by scandum** [comment]
The quad swap provides 100% optimal swapping at 4 items, so increasing this to 8 or 16 won't make this any more than 100%.

**Comment by Rratic** [comment]
OK,thx
(seems that I'm really not a good coder

Constant optimization is sometimes quite useful,though
- Someone else told me about `radix sort`,and they say by using r=256,it can make the best use of `Cache`.
- I heard that `++i` works quicker than `i++`.

![loading...](https://user-images.githubusercontent.com/73381027/106622459-8e3cdb80-65ae-11eb-854c-6868f6dc5fe9.jpg)
