### ISSUE TITLE
Bug in quadsort.h

### ISSUE THREAD

**Issue by Rratic** [scandum/quadsort#14]
```cpp
case sizeof(long long):// line322
	return quadsort64(array, nmemb, cmp);

case sizeof(long double):// line325
	return quadsort128(array, nmemb, cmp);
```
Sometimes both `long long` and `long double` are 64-bit

**Comment by Rratic** [comment]
Why not write 8,16,32,64 and 128 **directly** ?

**Comment by scandum** [comment]
A long double is 96 bit on some platforms. I guess in the case both `long long` and `long double` are 64 bit, compilation would fail.

The only real solution would be a typeless implementation, but I haven't felt in the mood to tackle that yet.

**Comment by Rratic** [comment]
Yeah,
the code is so difficult to understand that I guess it's hard to make a typeless implementation.
