### ISSUE TITLE
[Question] Just trying to understand mysterious (for me) `else`

### ISSUE THREAD

**Issue by MiloszKrajewski** [scandum/quadsort#15]
Hi,

I'm trying to understand how some bits works, and I'm slightly puzzled by mysterious `else`:

In [parity_swap_eight](https://github.com/scandum/quadsort/blob/16f83b63cc3e67698c5ff4c335df1451c7f9af9e/src/quadsort.c#L93) and [parity_tail_swap_eight](https://github.com/scandum/quadsort/blob/16f83b63cc3e67698c5ff4c335df1451c7f9af9e/src/quadsort.c#L177). 

What adds to my confusion is the fact that I **thought** that I understood [parity_swap_sixteen](https://github.com/scandum/quadsort/blob/16f83b63cc3e67698c5ff4c335df1451c7f9af9e/src/quadsort.c#L136) where after sorting 4 blocks x 4 items you check if it is a case when they are all "in row" so no need to merge anything.

I thought same thing happens in `parity_swap_eight`, but this `else` puzzles me.

Regards,
Milosz

**Comment by scandum** [comment]
The else there is optional. What it does is that it only checks if the 8 elements are fully sorted if element 7 and 8 are sorted.

If elements 7 and 8 aren't sorted it's unlikely the rest is.

**Comment by MiloszKrajewski** [comment]
Thank you. Sorry for keeping this issue open for that long.
At first I needed to digest it and ask some more questions and then I forgot.
Thanks again!
