### ISSUE TITLE
Some compilation errors

### ISSUE THREAD

**Issue by waruqi** [scandum/quadsort#17]
I am adding quadsort as package into xmake-repo repository, but I meet some compilation errors.

https://github.com/xmake-io/xmake-repo/pull/1790

### Error 1 for ios arm64, android armeabi-v7a and cross toolchains (muslcc arm)

https://github.com/xmake-io/xmake-repo/actions/runs/4099518400/jobs/7069506843
https://github.com/xmake-io/xmake-repo/actions/runs/4099518385/jobs/7069506091

```
checkinfo: ...amdir/core/sandbox/modules/import/core/tool/compiler.lua:84: @programdir/modules/core/tools/gcc.lua:713: /home/runner/.config/.xmake/packages/f/fluxsort/2023.02.05/aa60a67a14f44c54abbe30ae453ecfb9/include/quadsort.h:322:8: error: duplicate case value '8'
                case sizeof(long double):
                     ^
/home/runner/.config/.xmake/packages/f/fluxsort/2023.02.05/aa60a67a14f44c54abbe30ae453ecfb9/include/quadsort.h:318:8: note: previous case defined here
                case sizeof(long long):
                     ^
In file included from /dev/shm/.xmake1001/230206/_3B3636D6A724[48](https://github.com/xmake-io/xmake-repo/actions/runs/4099518400/jobs/7069506843#step:5:49)F693B42B70C050A25B.c:2:
/home/runner/.config/.xmake/packages/f/fluxsort/2023.02.05/aa60a67a14f44c54abbe30ae453ecfb9/include/fluxsort.h:246:8: error: duplicate case value '8'
                case sizeof(long double):
                     ^
/home/runner/.config/.xmake/packages/f/fluxsort/2023.02.05/aa60a67a14f44c54abbe30ae4[53](https://github.com/xmake-io/xmake-repo/actions/runs/4099518400/jobs/7069506843#step:5:54)ecfb9/include/fluxsort.h:243:8: note: previous case defined here
                case sizeof(long long):
```

### Error2 on windows

https://github.com/xmake-io/xmake-repo/actions/runs/4099518378/jobs/7069506679

```
C:\Users\runneradmin\AppData\Local\.xmake\packages\f\fluxsort\2023.02.05\b8a2a0e1a6f142e7aa83b7a7cf086eb4\include\quadsort.h(37): fatal error C1083:
 Cannot open include file: 'stdalign.h': No such file or directory
```

**Comment by scandum** [comment]
Error 1 for ios arm64, android armeabi-v7a and cross toolchains (muslcc arm)
-------------------------------------------------------------------------------------

My best guess is that a long double is 64 bits on that platform. A bit unusual.

You'll have to change the code like this in that case:
```c
//                case sizeof(long double):
                   case 16:
                         quadsort128(array, nmemb, cmp);
                        return;
```
And:
```
                default:
//                        assert(size == sizeof(char) || size == sizeof(short) || size == sizeof(int) || size == sizeof(long long) || size == sizeof(long double));
                        assert(size == sizeof(char) || size == sizeof(short) || size == sizeof(int) || size == sizeof(long long) || size == 16);
```

Error2 on windows
---------------------

```
//#include <stdalign.h>
```
Just comment out the #include, it is not required and was accidentally left there.

**Comment by scandum** [comment]
One more thing, you will also need to define a custom 128 bit type, so change this code as well:
```c
/*
#define VAR long double
#define FUNC(NAME) NAME##128
#include "quadsort.c"
#undef VAR
#undef FUNC
*/

typedef struct {char bytes[16];} struct128;
#define VAR struct128
#define FUNC(NAME) NAME##128

#include "quadsort.c"

#undef VAR
#undef FUNC
```

**Comment by scandum** [comment]
Good point, I'll try to update quadsort today so it will compile out of the box.

**Comment by scandum** [comment]
@waruqi I've updated quadsort.h, would you mind checking if it compiles without errors?

**Comment by waruqi** [comment]
But I don't see any new commits, the most recent one being two days ago.

**Comment by scandum** [comment]
My bad, I forgot to push. It should be there now.

**Comment by waruqi** [comment]
I have updated it and re-trigger ci test. https://github.com/xmake-io/xmake-repo/pull/1790

Can you update fluxsort too?

**Comment by waruqi** [comment]
It works fine now.

**Comment by scandum** [comment]
I've updated fluxsort just now. I'll have blitsort and crumsort updated within an hour as well.

**Comment by scandum** [comment]
Alright, I got it all updated. Thanks for letting me know and adding them as a package!

**Comment by waruqi** [comment]
It works fine, thanks. I have merged them.
